# Generated by Django 5.0.6 on 2025-05-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_remove_campaign_goal_amount_campaign_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
